version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "uuid"
        versions:
          - "14.0.0" # Ignore this specific version if causing issues
